### ISSUE TITLE
Jail doesn't do anything

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#10]
Right now when a player is sent to jail (by rolling doubles thrice, or by landing on "Go To Jail") they are not trapped in jail for 3 turns. This needs to be implemented. Remember, they may pay $50 at the beginning of their turn to exit jail, or they may try to roll doubles to leave jail. If they pay $50, they are allowed to roll on that turn. If they roll doubles, they exit jail and advance that many spaces. 
See (jail section): https://www.hasbro.com/common/instruct/Monopoly_Vintage.pdf

As always, message me on discord (indev31 / Adam Gulde) and comment below and I'll assign you this issue.

**Comment by Jexc0de** [comment]
I can take this since I've already worked on the turn based parts of the game. (Might take a couple days as I have an exam upcoming so assign it if that delay is okay with you)

**Comment by adamgulde** [comment]
Assigned!

**Comment by Ossedda** [comment]
I'd like to work on fixing this as well

**Comment by adamgulde** [comment]
closed by #64
