### ISSUE TITLE
update movement when chance card drawn

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#16]
You'll notice when a player draws a chance / cc chest card and it moves their token (for example, to reading railroad), the player will not be charged if another player owns it nor will they have the option to buy it. Adding a bit more logic to the respective *match / case* line here should help. 

The offending chance cards are as follows (see ascii.txt):  5, 6, 7, 10 (i think), 14

Please test each before you submit a PR.

**Comment by RunDMC2** [comment]
I could try and get this fixed in the next few days, could I get it assigned?

**Comment by adamgulde** [comment]
@RunDMC2 update?

**Comment by RunDMC2** [comment]
just submitted a pr, I had to fix another quick bug that came up since the last time I talked to you but everything should be all good now
