### ISSUE TITLE
Calculator module (modules.py) implement as stack

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#2]
Stacks (data structure) are perfect to implement multi-operator calculators. Currently, the calculator module, located in modules.py, uses a naive operation system. Implementing a stack would make the calculator module much more robust. 

If you're taking or have taken DSA, this is a pretty straightforward problem :)

===========
Respond below (first come, first serve) if you'd like to pick up this issue

**Comment by AmariN12** [comment]
I'd like to work on this issue!

**Comment by adamgulde** [comment]
Assigned!
