### ISSUE TITLE
History tab printing error when chance/cc cards drawn

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#21]
![image](https://github.com/user-attachments/assets/07119503-7812-43e2-be57-662df35f41b4)
Occasionally the history tab has some printing artifacts that appear semi-randomly. This seems to be triggered by drawing a chance or cc card, so check the update_history function and see how text is printed there during a card draw. This is just my idea tho I'm not exactly sure if that's the exact reason every time. 
**Steps to recreate:**
1. Start a new game
2. Have chance / cc cards drawn either by playing randomly or setting up a unit test
3. Play the game long enough for the history tab to be full and start scrolling upwards. (This is because, as you'll notice in the screenshot at the bottom, the artifacts do not appear when the text is not "scrolling," that is, when it isn't full at the start of a game.) 
4. Once history tab is full, draw a chance / cc card, end turn, and continue playing. You will probably begin to see these artifacts as the game continues as cards are drawn and the history continues to scroll. 

![image](https://github.com/user-attachments/assets/300cd230-40c9-4fd6-ad8f-850d76aa8099)

**Comment by jordanbrotherton** [comment]
May I be assigned to this issue?
