### ISSUE TITLE
Casino module: blackjack & coin flip

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#32]
Good first issue to get started with modules development. Remember that the ONLY screen space you have to work with is the rows and cols variables from screenspace.py, aka 1/2 of WIDTH and HEIGHT, aka 20 rows by 75 columns. 

If you're the first to either of the casino issues (see #31), then you may also begin working on a general casino module framework where players can select between different games. Something like below:

------ CASINO MODULE -------
Select game:
> Blackjack
> Coin Flip
> etc...
> exit
------ ....

If you're not familiar with coin flip, it's the simplest form of gambling: choose heads or tails, a win is x2 your wager.

**Comment by jordanbrotherton** [comment]
May I be assigned to this issue?
