### ISSUE TITLE
Implement rolling doubles

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#5]
Currently if the 2 dice equal each other, a notification is added to the history log BUT the player doesn't actually get to roll again. Easy fix.

===========
Respond below (first come, first serve) if you'd like to pick up this issue

**Comment by Jexc0de** [comment]
I'll talk a crack at this, I just got the repo and I'm taking it all in so it might be a couple days.

**Comment by adamgulde** [comment]
Assigned!

**Comment by adamgulde** [comment]
resolved by #12
