### ISSUE TITLE
Screen Formatting / Scaling / Printing

### ISSUE THREAD

**Issue by adamgulde** [ufosc/TERMINALMONOPOLY#9]
There are a LOT of issues with printing to the screen due to the nature of printing directly to the Terminal. Below are some of the issues that currently need to be addressed:

1. PRIMARY ISSUE: Starting programs (especially **monopoly.py** and **player.py**) in non-fullscreen or with a terminal size less than the minimum size causes many printing issues which are only partly recovered when the screen is refreshed.
2. Resizing the screen often leads to printing issues. **Using zoom in (ctrl + or ctrl -) may be helpful to solve this** 
3. "calc" module is not formatted well (not centered or left justified.. inconsistent for both)
4. "deed" command in **player.py** is incorrectly formatted and tears into the module to the side.

===========
Respond below (first come, first serve) if you'd like to pick up this issue

**Comment by NPKLTacocat** [comment]
I haven't solved all the issues in here yet but I've finished a function to force monopoly.py and player.py to start in fullscreen mode. can you make a separate issue for that and assign it to me so that we have something to work with for the time being?

**Comment by NPKLTacocat** [comment]
I will take on the issue 1 and 2, can I get assigned to this

**Comment by jordanbrotherton** [comment]
I will take on issue 5, may I be assigned to it? I will also fix manage properties
